# Generated by Django 2.0.6 on 2019-03-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameCollectionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectormodel',
            old_name='Password1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='collectormodel',
            old_name='Password2',
            new_name='password2',
        ),
    ]
